/*
 Navicat Premium Data Transfer

 Source Server         : test
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : C##MOMMYCARE

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 23/05/2023 14:58:57
*/


-- ----------------------------
-- Table structure for ADDRESSES
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."ADDRESSES";
CREATE TABLE "C##MOMMYCARE"."ADDRESSES" (
  "ADDRESS_ID" NUMBER VISIBLE NOT NULL,
  "UNIT_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "STREET_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "ADDRESS_LINE" VARCHAR2(255 BYTE) VISIBLE,
  "CITY" VARCHAR2(50 BYTE) VISIBLE,
  "REGION" VARCHAR2(50 BYTE) VISIBLE,
  "POSTAL_CODE" VARCHAR2(50 BYTE) VISIBLE,
  "COUNTRY" VARCHAR2(50 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ADDRESSES
-- ----------------------------

-- ----------------------------
-- Table structure for DOCTORS
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."DOCTORS";
CREATE TABLE "C##MOMMYCARE"."DOCTORS" (
  "DOCTOR_ID" NUMBER VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "FULL_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "SPECIALIZATION" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "WORKPLACE" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DOCTORS
-- ----------------------------

-- ----------------------------
-- Table structure for HOSPITALS
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."HOSPITALS";
CREATE TABLE "C##MOMMYCARE"."HOSPITALS" (
  "HOSPITAL_ID" NUMBER VISIBLE NOT NULL,
  "FULL_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "ADDRESS_ID" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of HOSPITALS
-- ----------------------------

-- ----------------------------
-- Table structure for PATIENT_DOCTOR_APPOINTMENT
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."PATIENT_DOCTOR_APPOINTMENT";
CREATE TABLE "C##MOMMYCARE"."PATIENT_DOCTOR_APPOINTMENT" (
  "PATIENT_ID" NUMBER VISIBLE,
  "APPOINTMENT_DATE" DATE VISIBLE,
  "DOCTOR_ID" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENT_DOCTOR_APPOINTMENT
-- ----------------------------

-- ----------------------------
-- Table structure for PATIENT_HOSPITAL_APPOINTMENT
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."PATIENT_HOSPITAL_APPOINTMENT";
CREATE TABLE "C##MOMMYCARE"."PATIENT_HOSPITAL_APPOINTMENT" (
  "PATIENT_ID" NUMBER VISIBLE,
  "APPOINTMENT_DATE" DATE VISIBLE,
  "HOSPITAL_ID" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PATIENT_HOSPITAL_APPOINTMENT
-- ----------------------------

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##MOMMYCARE"."USERS";
CREATE TABLE "C##MOMMYCARE"."USERS" (
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "FULL_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "WEIGHT" FLOAT(126) VISIBLE,
  "HEIGHT" FLOAT(126) VISIBLE,
  "DATE_OF_BIRTH" DATE VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "PROB_DELIVERY_DATE" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##MOMMYCARE"."USERS" VALUES ('1', 'nazmuntony', 'MST NAZMUN NAHAR', NULL, NULL, NULL, 'nazmuntony@gmail.com', '1234', NULL);

-- ----------------------------
-- Sequence structure for ADDRESS_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##MOMMYCARE"."ADDRESS_SEQUENCE";
CREATE SEQUENCE "C##MOMMYCARE"."ADDRESS_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for DOCTOR_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##MOMMYCARE"."DOCTOR_SEQUENCE";
CREATE SEQUENCE "C##MOMMYCARE"."DOCTOR_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for HOSPITAL_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##MOMMYCARE"."HOSPITAL_SEQUENCE";
CREATE SEQUENCE "C##MOMMYCARE"."HOSPITAL_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for USER_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##MOMMYCARE"."USER_SEQUENCE";
CREATE SEQUENCE "C##MOMMYCARE"."USER_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table ADDRESSES
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."ADDRESSES" ADD CONSTRAINT "SYS_C009833" PRIMARY KEY ("ADDRESS_ID");

-- ----------------------------
-- Triggers structure for table ADDRESSES
-- ----------------------------
CREATE TRIGGER "C##MOMMYCARE"."ADDRESS_BIN" BEFORE INSERT ON "C##MOMMYCARE"."ADDRESSES" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.ADDRESS_ID IS NULL
THEN
:NEW.ADDRESS_ID:=ADDRESS_SEQUENCE.NEXTVAL;
END IF;
END;
/

-- ----------------------------
-- Primary Key structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009842" PRIMARY KEY ("DOCTOR_ID");

-- ----------------------------
-- Uniques structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009843" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009844" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009839" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009840" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009841" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table HOSPITALS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."HOSPITALS" ADD CONSTRAINT "SYS_C009836" PRIMARY KEY ("HOSPITAL_ID");

-- ----------------------------
-- Uniques structure for table HOSPITALS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."HOSPITALS" ADD CONSTRAINT "SYS_C009837" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table HOSPITALS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."HOSPITALS" ADD CONSTRAINT "SYS_C009834" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."HOSPITALS" ADD CONSTRAINT "SYS_C009835" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009809" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009810" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009811" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009806" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009807" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."USERS" ADD CONSTRAINT "SYS_C009808" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table USERS
-- ----------------------------
CREATE TRIGGER "C##MOMMYCARE"."USER_BIN" BEFORE INSERT ON "C##MOMMYCARE"."USERS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.USER_ID IS NULL
THEN
:NEW.USER_ID:=USER_SEQUENCE.NEXTVAL;
END IF;
END;

/*DROP SEQUENCE USER_SEQUENCE;*/;

-- ----------------------------
-- Foreign Keys structure for table DOCTORS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."DOCTORS" ADD CONSTRAINT "SYS_C009845" FOREIGN KEY ("WORKPLACE") REFERENCES "C##MOMMYCARE"."HOSPITALS" ("HOSPITAL_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table HOSPITALS
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."HOSPITALS" ADD CONSTRAINT "SYS_C009838" FOREIGN KEY ("ADDRESS_ID") REFERENCES "C##MOMMYCARE"."ADDRESSES" ("ADDRESS_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PATIENT_DOCTOR_APPOINTMENT
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."PATIENT_DOCTOR_APPOINTMENT" ADD CONSTRAINT "SYS_C009846" FOREIGN KEY ("PATIENT_ID") REFERENCES "C##MOMMYCARE"."USERS" ("USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."PATIENT_DOCTOR_APPOINTMENT" ADD CONSTRAINT "SYS_C009847" FOREIGN KEY ("DOCTOR_ID") REFERENCES "C##MOMMYCARE"."DOCTORS" ("DOCTOR_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PATIENT_HOSPITAL_APPOINTMENT
-- ----------------------------
ALTER TABLE "C##MOMMYCARE"."PATIENT_HOSPITAL_APPOINTMENT" ADD CONSTRAINT "SYS_C009848" FOREIGN KEY ("PATIENT_ID") REFERENCES "C##MOMMYCARE"."USERS" ("USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##MOMMYCARE"."PATIENT_HOSPITAL_APPOINTMENT" ADD CONSTRAINT "SYS_C009849" FOREIGN KEY ("HOSPITAL_ID") REFERENCES "C##MOMMYCARE"."HOSPITALS" ("HOSPITAL_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
